// ============================================================================
// Event Viewer
// Copyright (C) 2023 Aiko Fujimoto & Contributors
//
// Licensed under MIT
// ============================================================================

const fs = require('fs')
const path = require('path')
const pkg = require('../package.json')

const buildRoot = path.join(__dirname, '../dist/')
const code = fs.readFileSync(path.join(buildRoot, './bundle.js'), 'utf-8')
const header =
  '// ==UserScript==\n' +
  '// @name        Doujin Event Viewer\n' +
  '// @namespace   Doujin Event Viewer\n' +
  '// @author      Aiko Fujimoto & Contributors\n' +
  '// @description Adds Viewable Events to specific event dates\n' +
  '// @match       *://*/*\n' +
  '// @version     ' + pkg.version + '\n' +
  '// @grant\n' +
  '// ==/UserScript==\n'

const filename = `doujin-event-viewer-${pkg.version}.stable.user.js`
fs.writeFileSync(path.join(buildRoot, `./${filename}`), `${header}${code}`, 'utf-8')

// Reset event.json after build
fs.writeFileSync(path.join(__dirname, '../src/events.json'), '[]\n', 'utf-8')

// Cleanup files generated by webpack
fs.readdirSync(buildRoot)
  .forEach(item => {
    if (!item.startsWith('doujin-event')) {
      fs.unlinkSync(path.join(buildRoot, item))
    }
  })
